---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2022/8/2 6:59
---
local am516 = {
    s7 = require("s7"),
    handle = nil,
    ip = "192.168.1.10",
    --ip = "192.168.8.201",
    rack = 0,
    slot = 1,
}

function am516:open()
    self.handle = self.s7.Connect(self.ip, self.rack, self.slot)
end

function am516:readString(db, start, size)
    return self.s7.ReadString(self.handle, db, start, size)
end

function am516:readBool(db, start, bit)
    return self.s7.ReadBool(self.handle, db, start, bit)
end

function am516:readWord(db, start)
    return self.s7.ReadU16(self.handle, db, start)
end

function am516:readI16(db, start)
    return self.s7.ReadI16(self.handle, db, start)
end

am516:open()

return am516
