---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepen.
--- DateTime: 2024/5/21 18:07
---

bus = {
    id = 0,
    rooms = {},
}

function bus:publish(topic, data)
    timer.push(0, function()
        local m = self.rooms[topic]
        for id, cbk in pairs(m) do
            if cbk~=nil then
                cbk(data)
            end
        end
    end)
end

function bus:subscribe(publisher, callback)
    local m = self.rooms[topic]
    if m == nil then
        m = {}
        self.rooms[topic] = m
    end
    --????????????????
    m[publisher] = callback
    return function()
        m[publisher] = nil
    end
end

function bus:remove(topic, id)
    local m = self.rooms[topic]
    if m == nil then
        return
    end
    m[id] = nil
end

return bus