---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepen.
--- DateTime: 2024/5/21 18:07
---

local bus = {
    id = 0,
    rooms = {},
}

function bus:publish(topic, data)
    local m = self.rooms[topic]
    for _, cbk in pairs(m) do
        if cbk~=nil then
            cbk(data)
        end
    end
end

function bus:subscribe(topic, callback)
    self.id = self.id+1
    local m = self.rooms[topic]
    if m == nil then
        m = {}
        self.rooms[topic] = m
    end
    local id = self.id
    m[id] = callback
    return function()
        m[id] = nil
    end
end

function bus:remove(topic, id)
    local m = self.rooms[topic]
    if m == nil then
        return
    end
    m[id] = nil
end

return bus