---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local fqc = {
    name = "fqc",
    part = "",
}

function fqc:execute()
    changeState(self, "fqcs1")
    return self
end


function fqc:onEvent(event)
    --print("三色灯状态", event.conf.plc:readI16(27,16))
end

return fqc