---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepen.
--- DateTime: 2024/5/22 5:12
---
--- line »·–‘œﬂ
---
local line = {
    machines = { "r1", "r2", "r3", "r4", "w1", "w2", "w3", "w4", "z1", "z2", "t1", "t2", "fqc", "led" },
    name = "am516",
}

function line:execute()
    for _, name in ipairs(self.machines) do
        local m = require(name)
        m.line = self
        m:execute()
        for _, s in ipairs(m.states) do
            local state = require(s)
            state.m = m
            state:init_subscribe()
        end
    end
end

function line:run()
    state.running = true
    state:setLed("green")
    bus:publish(self.name,'run', {})
end

function line:stop()
    state.running = false
    state.led.color = "yellow"
    self:publish(self.name,'stop', {})
end

function line:pause()
    self:publish(self.name,'pause',{})
end

function line:onEvent(data)

end

return line

