---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:14
---
require("state")
require("timer")
require("db")
require("utils")

local main = {}

function main:Run()
    print("lua inside")
    print("main.Run")
    self.line = require("line")
    self.line:execute()
    self.line:run()
    return self
end

return main