---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepen.
--- DateTime: 2024/5/21 5:59
---

local process = {
    station = {
        pt = {
            { 2, 0, 3, 0 }, --- Pi at writer 1
            { 2, 3, 0, 0 }, --- Pi at writer 2
            { 0, 3, 4, 0 }, --- Pi at writer 3
            { 0, 3, 0, 5 }, --- Pi at writer 4

        },
    },
    fqc = {
        pt = 1,
    }


}

--- 返回展位的加工实践
function process:spt(station, process_index)
    return self.station.pt[station][process_index]
end

return process