---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local r1 = {
    name = "r1",
    part = "",
}

function r1:execute()
    changeState(self, "r1s1")
    return self
end

function r1:onEvent(event)
    --print("三色灯状态", event.conf.plc:readI16(27,16))
end

return r1