---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local r1 = {
        s1 = require("r1s1"),
        s2 = require("r1s2"),
        name = "r1",
        part = "",
        currentState  = nil,
}

function r1:execute(line)
    self.line = line
    changeState(self, "r1s1")
    return self
end

function r1:onEvent(event)
    --print(event)
    --print("三色灯状态", event.conf.plc:readI16(27,16))

    --print("target", event.target)
    --print("data", event.data)
    --print("data.value", event.data.value)
    --print("self.currentState", self.currentState.name)
    if self.currentState ~= nil then
        self.currentState:onEvent(self, event)
    end
end

return r1