---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local r2 = {
    name = "robot_arm_2",
    currentState = nil,
    states ={'r2s1','r2s2','r2s3','r2s4'},
    line = nil,
}

function r2:execute()
    changeState(self, "r2s1")
end


function r2:onEvent(data)

end

return r2