---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local r2 = {
    name = "robot 2",
}

function r2:execute()
    changeState(self, "r2s1")
    return self
end


function r2:onEvent(event)
end

return r2