---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local r3 = {
    name = "robot 3",
    bus = "516.am",
}

function r3:execute()
    changeState(self, "r3s1")
    return self
end


function r3:onEvent(event)
    --require("nats").SubscribeFunc(self.bus, "am:r1")
end

return r3