---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local r4 = {
    s1 = require("r4s1"),
    s2 = require("r4s2"),
    name = "robot 2",
    currentState  = null
}

function r4:execute(line)
    print(self.name)
    self.line = line
    changeState(self, "r4s1")
end


function r4:onEvent(event)
    print("onevent")
    --changeState(m, "r4s1")
    --self.line:subscribe(self.)
end

return r4