---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepen.
--- DateTime: 2024/5/22 6:56
--- state is a global variable which contains states of the line

state = {
    running = false,
    led = {
        color = "",
    },
}

function state:set(f)
    f(self)
    print("state is changed")
    return self
end

return state