---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local t1 = {
    name = "transport_1",
    part = "",
}

function t1:execute()
    changeState(self, "t1s1")
    return self
end


function t1:onEvent(event)
    --print("三色灯状态", event.conf.plc:readI16(27,16))
end

return t1