---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local w1 = {
    name = "robot1",
    part = "",
}

function w1:execute()
    changeState(self, "w1s1")
    return self
end


function w1:onEvent(event)
    --print("三色灯状态", event.conf.plc:readI16(27,16))
end

return w1