---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local w2 = {
    name = "w2",
    part = "",
}

function w2:execute()
    changeState(self, "w2s1")
    return self
end

function w2:onEvent(event)
    --print("三色灯状态", event.conf.plc:readI16(27,16))
end

return w2