---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local w4 = {
    name = "write_4",
    part = "",
}

function w4:execute()
    changeState(self, "w4s1")
    return self
end

function w4:onEvent(event)
end

return w4