---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2021/10/21 17:51
---

local z2 = {
    name = "stop_2",
    part = "",
}

function z2:execute()
    changeState(self, "z2s1")
    return self
end

return z2